#!/usr/bin/env python3
"""Generate an Ed25519 API key and register it against your wallet.

The Arcus web app (https://testnet.arcus.xyz/api-keys) does the same thing in a
few clicks and is the recommended path. Use this when you need it scripted.

    pip install -r requirements-onboard.txt
    python tools/onboard.py --private-key 0x<wallet key> --days 30

Writes the resulting credentials to .env (never overwriting an existing one
without --force). The wallet private key is used ONLY to sign the registration
locally; it is never sent anywhere and never written to disk.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from arcusbot.config import MAINNET_REST, TESTNET_REST  # noqa: E402
from arcusbot.signing import canonical_json  # noqa: E402


def call(base: str, method: str, path: str, body: dict | None = None) -> dict:
    data = canonical_json(body).encode() if body is not None else None
    req = urllib.request.Request(base + path, data=data, method=method,
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            return json.loads(resp.read() or b"{}")
    except urllib.error.HTTPError as exc:
        raise SystemExit(f"HTTP {exc.code} on {path}: {exc.read().decode(errors='replace')}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Register an Arcus API key")
    ap.add_argument("--private-key", required=True, help="wallet private key (0x...), used locally only")
    ap.add_argument("--name", default="arcus-testnet-bot")
    ap.add_argument("--days", type=int, default=30, help="validity, 1-180")
    ap.add_argument("--account-index", type=int, default=0)
    ap.add_argument("--network", choices=["testnet", "mainnet"], default="testnet")
    ap.add_argument("--env-file", default=str(REPO_ROOT / ".env"))
    ap.add_argument("--force", action="store_true", help="overwrite an existing .env")
    args = ap.parse_args()

    try:
        from cryptography.hazmat.primitives.asymmetric import ed25519
        from eth_account import Account
        from eth_account.messages import encode_defunct
    except ImportError:
        raise SystemExit("missing deps — run: pip install -r requirements-onboard.txt")

    if not 1 <= args.days <= 180:
        raise SystemExit("--days must be between 1 and 180")

    base = TESTNET_REST if args.network == "testnet" else MAINNET_REST
    wallet = Account.from_key(args.private_key)

    priv = ed25519.Ed25519PrivateKey.generate()
    secret_hex = priv.private_bytes_raw().hex()
    api_key = priv.public_key().public_bytes_raw().hex()

    valid_until = int(time.time() * 1000) + args.days * 86_400_000
    message = canonical_json({
        "apiWalletName": args.name,
        "apiWalletPublicKey": api_key,
        "validUntil": valid_until,
    }).encode()
    signature = wallet.sign_message(encode_defunct(primitive=message))

    print(f"registering key {api_key[:16]}… for {wallet.address} on {args.network}")
    created = call(base, "POST", "/v1/createApiKey", {
        "address": wallet.address,
        "publicKey": api_key,
        "apiWalletName": args.name,
        "validUntil": valid_until,
        "signature": {"r": hex(signature.r), "s": hex(signature.s), "v": hex(signature.v)},
    })
    account_index = created.get("accountIndex", args.account_index)

    print("waiting for the key to go live", end="", flush=True)
    for _ in range(60):
        keys = call(base, "GET", f"/v1/apiKeys?address={wallet.address}")
        if any(k.get("apiKey") == api_key for k in keys.get("apiKeys", [])):
            print(" — live")
            break
        print(".", end="", flush=True)
        time.sleep(1)
    else:
        print("\nWARNING: key not visible yet; it may still be propagating")

    env_path = Path(args.env_file)
    if env_path.exists() and not args.force:
        print(f"\n{env_path} already exists — not overwriting. Add these lines yourself:\n")
        print(f"ARCUS_ADDRESS={wallet.address}")
        print(f"ARCUS_API_SECRET={secret_hex}")
        print(f"ARCUS_ACCOUNT_INDEX={account_index}")
        return 0

    env_path.write_text(
        f"# generated by tools/onboard.py at {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n"
        f"# API signing key — treat as a secret; it authorizes trading (not withdrawals).\n"
        f"ARCUS_NETWORK={args.network}\n"
        f"ARCUS_ADDRESS={wallet.address}\n"
        f"ARCUS_API_SECRET={secret_hex}\n"
        f"ARCUS_ACCOUNT_INDEX={account_index}\n"
        f"BOT_MODE=dry-run\n",
        encoding="utf-8",
    )
    env_path.chmod(0o600)
    print(f"\ncredentials written to {env_path} (mode 600)")
    print(f"  address       {wallet.address}")
    print(f"  api key       {api_key}")
    print(f"  accountIndex  {account_index}")
    print(f"  valid until   {time.strftime('%Y-%m-%d', time.gmtime(valid_until / 1000))}")
    print("\nNext: fund the account (Testnet Deposit button, or tools/fund_testnet.py),")
    print("      then run:  python -m arcusbot preflight")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
